version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: stc_pass
      MYSQL_DATABASE: stc_dbName
      MYSQL_USER: stc12345
      MYSQL_PASSWORD: stc12345
    ports:
      - "3306:3306"  # Expose MySQL port

  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"  # Expose Spring Boot app port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stc_dbName?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: stc12345
      SPRING_DATASOURCE_PASSWORD: stc12345
    depends_on:
      - db
